# Generated by Django 3.2.25 on 2024-11-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241014_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Ingredients',
            field=models.ManyToManyField(related_name='recipes', to='core.Ingredient'),
        ),
    ]
