# Generated by Django 3.2.25 on 2024-11-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='core.Ingredient'),
        ),
    ]
