# Generated by Django 3.2.25 on 2024-11-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
